package com.dz.utilities.todoo.domains;
// Generated Aug 2, 2014 6:58:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * MainList generated by hbm2java
 */
@Entity
@Table(name = "main_list", catalog = "dz_todo_list")
public class MainList implements java.io.Serializable {

	private Integer seqId;
	private User user;
	private Date createdDate;
	private String listName;
	private String password;
	private String inactiveIndicator;
	private String publishedIndicator;
	private TodoItems todoItems;

	public MainList() {
	}

	public MainList(Date createdDate, String listName,
			String inactiveIndicator, String publishedIndicator) {
		this.createdDate = createdDate;
		this.listName = listName;
		this.inactiveIndicator = inactiveIndicator;
		this.publishedIndicator = publishedIndicator;
	}

	public MainList(User user, Date createdDate, String listName,
			String password, String inactiveIndicator,
			String publishedIndicator, TodoItems todoItems) {
		this.user = user;
		this.createdDate = createdDate;
		this.listName = listName;
		this.password = password;
		this.inactiveIndicator = inactiveIndicator;
		this.publishedIndicator = publishedIndicator;
		this.todoItems = todoItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "seqId", unique = true, nullable = false)
	public Integer getSeqId() {
		return this.seqId;
	}

	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "list_name", nullable = false, length = 300)
	public String getListName() {
		return this.listName;
	}

	public void setListName(String listName) {
		this.listName = listName;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "inactive_indicator", nullable = false, length = 1)
	public String getInactiveIndicator() {
		return this.inactiveIndicator;
	}

	public void setInactiveIndicator(String inactiveIndicator) {
		this.inactiveIndicator = inactiveIndicator;
	}

	@Column(name = "published_indicator", nullable = false, length = 1)
	public String getPublishedIndicator() {
		return this.publishedIndicator;
	}

	public void setPublishedIndicator(String publishedIndicator) {
		this.publishedIndicator = publishedIndicator;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "mainList")
	public TodoItems getTodoItems() {
		return this.todoItems;
	}

	public void setTodoItems(TodoItems todoItems) {
		this.todoItems = todoItems;
	}

}
