package com.dz.utilities.todoo.domains;
// Generated Aug 2, 2014 6:58:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TodoItems generated by hbm2java
 */
@Entity
@Table(name = "todo_items", catalog = "dz_todo_list")
public class TodoItems implements java.io.Serializable {

	private Integer seqId;
	private User user;
	private MainList mainList;
	private String itemTitle;
	private String itemDescription;
	private Date createdDate;
	private String completedIndicator;
	private Integer displayOrder;
	private String importantIndicator;
	private String inactiveIndicator;
	private int mainListSeqId;

	public TodoItems() {
	}

	public TodoItems(User user, MainList mainList, String completedIndicator,
			int mainListSeqId) {
		this.user = user;
		this.mainList = mainList;
		this.completedIndicator = completedIndicator;
		this.mainListSeqId = mainListSeqId;
	}

	public TodoItems(User user, MainList mainList, String itemTitle,
			String itemDescription, Date createdDate,
			String completedIndicator, Integer displayOrder,
			String importantIndicator, String inactiveIndicator,
			int mainListSeqId) {
		this.user = user;
		this.mainList = mainList;
		this.itemTitle = itemTitle;
		this.itemDescription = itemDescription;
		this.createdDate = createdDate;
		this.completedIndicator = completedIndicator;
		this.displayOrder = displayOrder;
		this.importantIndicator = importantIndicator;
		this.inactiveIndicator = inactiveIndicator;
		this.mainListSeqId = mainListSeqId;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "mainList"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "seqId", unique = true, nullable = false)
	public Integer getSeqId() {
		return this.seqId;
	}

	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public MainList getMainList() {
		return this.mainList;
	}

	public void setMainList(MainList mainList) {
		this.mainList = mainList;
	}

	@Column(name = "item_title", length = 200)
	public String getItemTitle() {
		return this.itemTitle;
	}

	public void setItemTitle(String itemTitle) {
		this.itemTitle = itemTitle;
	}

	@Column(name = "item_description", length = 4000)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "completed_indicator", nullable = false, length = 1)
	public String getCompletedIndicator() {
		return this.completedIndicator;
	}

	public void setCompletedIndicator(String completedIndicator) {
		this.completedIndicator = completedIndicator;
	}

	@Column(name = "display_order")
	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "important_indicator", length = 1)
	public String getImportantIndicator() {
		return this.importantIndicator;
	}

	public void setImportantIndicator(String importantIndicator) {
		this.importantIndicator = importantIndicator;
	}

	@Column(name = "inactive_indicator", length = 1)
	public String getInactiveIndicator() {
		return this.inactiveIndicator;
	}

	public void setInactiveIndicator(String inactiveIndicator) {
		this.inactiveIndicator = inactiveIndicator;
	}

	@Column(name = "main_list_seq_id", nullable = false)
	public int getMainListSeqId() {
		return this.mainListSeqId;
	}

	public void setMainListSeqId(int mainListSeqId) {
		this.mainListSeqId = mainListSeqId;
	}

}
