package com.dz.utilities.todoo.domains;
// Generated Aug 2, 2014 6:58:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "dz_todo_list")
public class User implements java.io.Serializable {

	private Integer seqId;
	private String firstName;
	private String lastName;
	private Date createdDate;
	private String userName;
	private String password;
	private Set<TodoItems> todoItemses = new HashSet<TodoItems>(0);
	private Set<MainList> mainLists = new HashSet<MainList>(0);

	public User() {
	}

	public User(String firstName, String lastName, Date createdDate,
			String userName, String password) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.createdDate = createdDate;
		this.userName = userName;
		this.password = password;
	}

	public User(String firstName, String lastName, Date createdDate,
			String userName, String password, Set<TodoItems> todoItemses,
			Set<MainList> mainLists) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.createdDate = createdDate;
		this.userName = userName;
		this.password = password;
		this.todoItemses = todoItemses;
		this.mainLists = mainLists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "seqId", unique = true, nullable = false)
	public Integer getSeqId() {
		return this.seqId;
	}

	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "user_name", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<TodoItems> getTodoItemses() {
		return this.todoItemses;
	}

	public void setTodoItemses(Set<TodoItems> todoItemses) {
		this.todoItemses = todoItemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<MainList> getMainLists() {
		return this.mainLists;
	}

	public void setMainLists(Set<MainList> mainLists) {
		this.mainLists = mainLists;
	}

}
